encoding    : UTF-8
exclude     : [vendor]

title       : Paryestih
subtitle    : Discover Geo-tagged Videos
author      : Kabir Das
home        : https://thedas.biz
github      : 
github_repo :
gh_pages    : 
